import fs from 'node:fs';
import path from 'node:path';
import { assertContractFile } from './contracts.mjs';
import { VERSION } from './constants.mjs';
import { abs, ensureDir, exists, readJson, shaFile, writeJson, writeText } from './fs-utils.mjs';
import { writeManifestLock } from './manifest.mjs';
import { assertPhase, readProjectId, setState, validateState } from './state.mjs';
import { targetRunnerCode } from './runner-template.mjs';

export function cmdFactoryBootstrap(opts, fail) {
  const target = abs(opts.target || '../target-project');
  assertPhase(target, ['planning-frozen'], 'factory bootstrap', fail);
  const hp = path.join(target, '.harness/planning');
  const handoffPath = path.join(hp, 'build-handoff.json');
  if (!exists(handoffPath)) fail('build-handoff.json이 없습니다.');
  assertContractFile('buildHandoff', handoffPath, fail);
  const handoff = readJson(handoffPath);
  const projectId = readProjectId(target) || handoff.projectId;
  const generated = [];
  const put = (rel, content) => { const p = path.join(target, rel); writeText(p, content); generated.push(rel); };
  const putJson = (rel, obj) => { const p = path.join(target, rel); writeJson(p, obj); generated.push(rel); };

  put('package.json', JSON.stringify({ name: projectId, version: '0.1.0', private: true, type: 'module', scripts: { test: "node -e \"console.log('test ok')\"", lint: "node -e \"console.log('lint ok')\"", typecheck: "node -e \"console.log('typecheck ok')\"" } }, null, 2) + '\n');
  put('apps/web/src/index.ts', `export const appName = ${JSON.stringify(handoff.projectName || projectId)};\n`);
  put('apps/api/src/server.ts', `export function health(){ return { ok: true }; }\n`);
  put('packages/shared/src/index.ts', `export const shared = true;\n`);
  put('packages/contracts/README.md', `# Contracts\n\nAPI contracts and shared schemas live here.\n`);
  put('infra/docker/compose.dev.yml', `services:\n  web:\n    image: node:22\n    working_dir: /workspace\n    volumes:\n      - ../../:/workspace\n    command: node -e \"console.log('dev placeholder')\"\n`);
  put('infra/docker/compose.preview.yml', `services:\n  preview:\n    image: node:22\n    working_dir: /workspace\n    volumes:\n      - ../../:/workspace\n    command: node -e \"console.log('preview placeholder')\"\n`);
  put('infra/docker/compose.prod.yml', `services:\n  app:\n    image: node:22\n    command: node -e \"console.log('prod placeholder')\"\n`);
  put('infra/caddy/Caddyfile', `:8080 {\n  respond \"Meta Harness preview placeholder\"\n}\n`);
  put('.devcontainer/devcontainer.json', JSON.stringify({ name: 'target-project-factory', image: 'mcr.microsoft.com/devcontainers/typescript-node:22', workspaceFolder: '/workspace' }, null, 2) + '\n');
  put('.codex/config.toml', `# Project-scoped Codex config placeholder\n# Keep credentials in user-level config or runtime secrets, not here.\n`);
  put('AGENTS.md', `# AGENTS.md — Target Project Factory Instructions

## Role

You are working inside a **Target Project Repo** generated by Meta Harness.
This repository is the source of truth for its own planning, code, infrastructure, CI/CD, and run artifacts.

## Required read order

1. AGENTS.md
2. .harness/state.yml
3. .harness/factory.yml
4. .harness/planning/build-handoff.json
5. .harness/planning/acceptance-criteria.json
6. The selected .harness/tasks/*.task.json
7. .harness/security/runtime-policy.yml

## Allowed behavior

- Implement only the selected task packet.
- Modify only paths in editableScope.
- Run only verification commands listed in the task packet or project scripts.
- Produce patch/report/artifacts under .harness/runs/<run-id>/.

## Forbidden behavior

Never edit:

- .env*
- infra/**/production/**
- .github/workflows/deploy-prod.yml
- long-lived credentials

Never send raw docs/code/logs to Meta Harness. Only sanitized signals are allowed.

## Definition of Done

A task is complete when:

- acceptance criteria are satisfied
- lint/typecheck/test pass or failure is reported clearly
- no forbidden path is modified
- patch.diff, run-result.json, and summary.md are produced
`);
  put('CLAUDE.md', `@AGENTS.md\n`);
  put('.github/workflows/ci.yml', `name: ci\non:\n  pull_request:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - run: npm test\n`);
  put('Makefile', `dev:\n\t@echo \"dev placeholder\"\n\npreview:\n\t@echo \"preview placeholder\"\n\ntest:\n\tnpm test\n\nlint:\n\tnpm run lint\n\ntypecheck:\n\tnpm run typecheck\n\nharness-run:\n\tnode .harness/bin/runner.mjs --task $(TASK) --adapter $(ADAPTER)\n`);
  put('.harness/bin/runner.mjs', targetRunnerCode());
  fs.chmodSync(path.join(target, '.harness/bin/runner.mjs'), 0o755);
  put('.harness/factory.yml', `schemaVersion: 1\nfactory:\n  id: ${projectId}\n  version: 0.1.0\n  generatedBy: meta-harness-platform-starter\n  generatorVersion: ${VERSION}\ngeneratedFrom:\n  buildHandoff: .harness/planning/build-handoff.json\n  buildHandoffHash: sha256:${shaFile(handoffPath)}\ncapabilities:\n  planning: true\n  bootstrap: true\n  mvpBuild: true\n  localWorktreeRunner: true\n  localTaskKubernetes: false\n  githubActions: true\n`);
  put('.harness/execution-profiles.yml', `defaultProfile: L0_LOCAL_WORKTREE\nprofiles:\n  L0_LOCAL_WORKTREE:\n    isolation:\n      filesystem: git-worktree-or-fallback\n      network: inherited-restricted\n      secrets: filtered-env\n    artifacts:\n      - patch.diff\n      - run-result.json\n      - summary.md\n  L1_CONTAINER_WORKER:\n    enabled: false\n  L2_KIND_NAMESPACE:\n    enabled: false\n  L3_GITHUB_ACTION:\n    enabled: false\n`);
  put('.harness/agents/adapters.yml', `defaultAdapter: shell\nadapters:\n  shell:\n    enabled: true\n    type: local-shell-mvp\n  codex:\n    enabled: false\n    type: codex-exec\n  claude:\n    enabled: false\n    type: claude-code\n  openhands:\n    enabled: false\n    type: openhands\n`);
  put('.harness/security/runtime-policy.yml', `phases:\n  setup:\n    network:\n      default: deny\n      allow:\n        - registry.npmjs.org\n        - api.github.com\n  worker:\n    network:\n      default: deny\n    forbiddenWrites:\n      - .env*\n      - **/*.pem\n      - **/*secret*\n      - **/*token*\n      - infra/**/production/**\n      - .github/workflows/deploy-prod.yml\n    commandPolicy:\n      default: deny\n      allow:\n        - node *\n        - npm test\n        - npm run *\n        - bash ./tests/*\n        - make *\n      deny:\n        - git push*\n        - npm publish*\n        - docker login*\n        - rm -rf .git*\n`);
  put('.harness/budgets.yml', `budgets:\n  default:\n    maxRuntimeMinutes: 20\n    maxRetries: 1\n    maxChangedFiles: 20\n    maxPatchLines: 800\n`);
  putJson('.harness/tasks/example.task.json', {
    schemaVersion: '1.0.0',
    taskId: 'ISSUE-001',
    taskType: 'frontend-ui',
    priority: 'P2',
    title: 'Harness run loop proof task',
    objective: 'Create a small generated frontend feature file to prove the harness run loop.',
    editableScope: ['apps/web/src/**', 'packages/shared/**', 'docs/**', 'tests/**'],
    forbiddenScope: ['.env*', 'infra/**/production/**', '.github/workflows/deploy-prod.yml'],
    acceptanceCriteria: [{ id: 'AC-001', text: 'The harness run creates patch.diff, run-result.json, and summary.md.' }],
    verifyCommands: ["node -e \"console.log('lint ok')\"", "node -e \"console.log('typecheck ok')\"", "node -e \"console.log('test ok')\""],
    commands: { verify: ["node -e \"console.log('lint ok')\"", "node -e \"console.log('typecheck ok')\"", "node -e \"console.log('test ok')\""] },
    budgets: { maxRuntimeMinutes: 20, maxRetries: 1, maxChangedFiles: 20, maxPatchLines: 800 },
    expectedArtifacts: ['patch.diff', 'run-result.json', 'summary.md']
  });
  ensureDir(path.join(target, '.harness/runs'));
  ensureDir(path.join(target, '.harness/tmp'));

  const manifestPath = writeManifestLock({ target, projectId, handoffPath, generated });
  const factoryPath = path.join(target, '.harness/factory.yml');
  assertContractFile('factory', factoryPath, fail);
  assertContractFile('manifest', manifestPath, fail);
  setState(target, {
    projectId,
    phase: 'factory-ready',
    fail,
    fields: {
      factoryManifestHash: `sha256:${shaFile(path.join(target, '.harness/manifest.lock'))}`
    }
  });
  validateState(target, fail);
  return `Project Factory bootstrapped: ${target}`;
}
